import test from 'node:test';
import assert from 'node:assert/strict';
import {createD1Rest} from '../scripts/lib/d1-rest.mjs';
import {makeDb} from './helpers/d1shim.mjs';
import {seedProject} from './helpers/seed.mjs';
import {runActions} from '../scripts/actions-runner.mjs';
import {claimJobs} from '../src/lib/db.js';
import {processJobs} from '../src/lib/orchestrator.js';
import {collectFdicSource} from '../src/lib/fdic.js';
const config={accountId:'a'.repeat(32),databaseId:'12345678-1234-1234-1234-123456789abc',token:'test-only',intervalMs:0,sleep:async()=>{}};
function remote(DB,maxCalls){return createD1Rest({...config,maxCalls,fetchImpl:async(_url,o)=>{const r=await DB.batch(JSON.parse(o.body).batch.map(x=>DB.prepare(x.sql).bind(...x.params)));return Response.json({success:true,result:r.map(x=>({...x,success:true}))});}});}
test('cleanup calls remain available after the work budget is exhausted',async()=>{const DB=remote(makeDb(),1);await DB.prepare('SELECT 1').first();await assert.rejects(DB.prepare('SELECT 2').first(),/budget_exhausted/);const row=await DB.withControl(()=>DB.prepare('SELECT 3 AS value').first());assert.equal(row.value,3);assert.equal(DB.remaining,0);assert.equal(DB.calls,2);await assert.rejects(DB.prepare('SELECT 4').first(),/budget_exhausted/);});
test('budget-limited scheduling returns a normal deferral and releases the durable runner lease',async()=>{const db=makeDb();await seedProject(db,{candidates:0,reviewer:0,episodes:0});db.raw.exec("UPDATE projects SET status='running'");const DB=remote(db,4);const out=await runActions({DB,EXTERNAL_RUNTIME:'github-actions',COMPUTE_EXECUTOR:'github-actions',MAX_JOBS_PER_TICK:1});assert.equal(out.status,'budget_deferred');assert.equal(out.failures,0);assert.ok(db.raw.prepare('SELECT lease_until FROM external_runner_leases').get().lease_until<=new Date().toISOString());});
test('a collection job is left queued when insufficient API budget remains',async()=>{const db=makeDb();const id=await seedProject(db,{candidates:0,reviewer:0,episodes:0});db.raw.prepare("INSERT INTO jobs(id,project_id,type,status,priority,payload_json,run_after,created_at,updated_at) VALUES('collect',?,'collect_project','queued',1,'{}','2000','2000','2000')").run(id);const DB=remote(db,100),env={DB,EXTERNAL_RUNTIME:'github-actions'};assert.equal((await claimJobs(env,1)).length,0);assert.equal(env.RUNNER_BUDGET_DEFERRED,true);const j=db.raw.prepare("SELECT status,attempts FROM jobs WHERE id='collect'").get();assert.equal(j.status,'queued');assert.equal(j.attempts,0);});
test('FDIC 1200 branch rows use bulk writes and resume the next linked episode',async()=>{const DB=makeDb(),id=await seedProject(DB,{candidates:0,reviewer:0,episodes:2}),now=new Date().toISOString();DB.raw.exec('UPDATE empirical_episodes SET year=2008');DB.raw.prepare("INSERT INTO data_sources(id,project_id,name,kind,url,method,headers_json,mapping_json,enabled,cadence_minutes,created_at) VALUES('s',?,'test','fdic_sod','https://api.fdic.gov/banks/sod','GET','{}','{}',1,10080,?)").run(id,now);for(let i=0;i<2;i++)DB.raw.prepare("INSERT INTO fdic_episode_links(id,project_id,episode_id,cert,institution_name,match_status,match_method,match_score,candidate_json,confirmed_at,created_at,updated_at) VALUES(?,?,?,?,'test','confirmed','manual',1,'{}',?,?,?)").run('l'+i,id,'ep_'+i,100+i,now,now,now);const old=globalThis.fetch;let writes=0;const wrapped={...DB,prepare(sql){if(sql.startsWith('INSERT INTO fdic_sod_observations'))writes++;return DB.prepare(sql);}};globalThis.fetch=async url=>{const u=new URL(url),filters=u.searchParams.get('filters'),cert=Number(/CERT:(\d+)/.exec(filters)?.[1]||100);return Response.json({meta:{total:1200},data:Array.from({length:1200},(_,i)=>({YEAR:2008,CERT:cert,UNINUMBR:i,BRNUM:i,STALPBR:'CA',DEPSUMBR:10}))});};try{const env={DB:wrapped,EXTERNAL_RUNTIME:'github-actions'},source=DB.raw.prepare("SELECT * FROM data_sources WHERE id='s'").get();let r=await collectFdicSource(env,id,source);assert.equal(r.errors.length,0);assert.equal(r.processed,1);assert.equal(r.partial,true);assert.equal(r.next_cursor,1);assert.equal(writes,3);assert.equal(DB.raw.prepare('SELECT COUNT(*) n FROM fdic_sod_observations').get().n,1200);r=await collectFdicSource(env,id,DB.raw.prepare("SELECT * FROM data_sources WHERE id='s'").get());assert.equal(r.partial,false);assert.equal(r.next_cursor,0);assert.equal(writes,6);assert.equal(DB.raw.prepare('SELECT COUNT(*) n FROM fdic_sod_observations').get().n,2400);}finally{globalThis.fetch=old;}});

test('mid-job budget exhaustion requeues the job without spending a failure attempt',async()=>{const db=makeDb(),id=await seedProject(db,{candidates:0,reviewer:0,episodes:0});db.raw.prepare("INSERT INTO jobs(id,project_id,type,status,priority,payload_json,run_after,created_at,updated_at) VALUES('advance',?,'advance_project','queued',1,'{}','2000','2000','2000')").run(id);const original=remote(db,3),DB={...original,get remaining(){return 1000;}};const result=await processJobs({DB,EXTERNAL_RUNTIME:'github-actions',COMPUTE_EXECUTOR:'github-actions',MAX_JOBS_PER_TICK:1});assert.equal(result[0].deferred,true);const job=db.raw.prepare("SELECT status,attempts,locked_at FROM jobs WHERE id='advance'").get();assert.equal(job.status,'queued');assert.equal(job.attempts,0);assert.equal(job.locked_at,null);});
