import test from 'node:test';
import assert from 'node:assert/strict';
import {createD1Rest,restStatement} from '../scripts/lib/d1-rest.mjs';
import {acquireRunner,heartbeatRunner,releaseRunner} from '../scripts/lib/actions-runtime.mjs';
import {runActions} from '../scripts/actions-runner.mjs';
import {makeDb} from './helpers/d1shim.mjs';
import {seedProject} from './helpers/seed.mjs';
import {processJobs,scheduleAll} from '../src/lib/orchestrator.js';
import {scheduleLab} from '../src/lib/lab.js';
import {computeCandidate} from '../src/lib/compute.js';
import {bust} from '../src/lib/memo.js';
const creds={accountId:'a'.repeat(32),databaseId:'12345678-1234-1234-1234-123456789abc',token:'test-only',intervalMs:0,sleep:async()=>{}};
test('public Worker cannot execute research jobs or lab tasks in Actions mode',async()=>{const env={COMPUTE_EXECUTOR:'github-actions',DB:{prepare(){throw Error('unexpected read');}}};assert.equal((await processJobs(env))[0].status,'waiting_for_github_actions');assert.equal((await scheduleAll(env)).transport,'github-actions');assert.equal((await scheduleLab(env)).status,'waiting_for_github_actions');await assert.rejects(computeCandidate(env,'missing','missing'),/compute_requires_github_actions/);});
test('D1 REST preserves binary bindings and SQL quoted question marks',()=>{const x=restStatement("SELECT '?' AS literal, ? AS data, ? AS value -- ?\n",[new Uint8Array([0,255,34]),"a'b"]);assert.match(x.sql,/X'00ff22'/);assert.deepEqual(x.params,["a'b"]);assert.match(x.sql,/SELECT '\?'/);assert.throws(()=>restStatement('SELECT ?',[{}]),/Unsupported/);});
test('D1 REST sends one transactional batch and honors a hard call budget',async()=>{let calls=0;const DB=createD1Rest({...creds,maxCalls:1,fetchImpl:async(_url,o)=>{calls++;assert.equal(o.headers.authorization,'Bearer test-only');assert.equal(JSON.parse(o.body).batch.length,2);return Response.json({success:true,result:[{success:true,results:[{x:1}],meta:{changes:1}},{success:true,results:[],meta:{changes:2}}]});}});const out=await DB.batch([DB.prepare('SELECT ? x').bind(1),DB.prepare('UPDATE example SET x=?').bind(2)]);assert.equal(out[1].meta.changes,2);assert.equal(calls,1);await assert.rejects(DB.prepare('SELECT 1').all(),/budget_exhausted/);});
test('global lease excludes other runners and stale owners cannot release new leases',async()=>{const DB=makeDb(),env={DB};const token=await acquireRunner(env);assert.ok(token);assert.equal(await acquireRunner(env),null);await heartbeatRunner(env,token);DB.raw.exec("UPDATE external_runner_leases SET lease_until='2000-01-01'");const next=await acquireRunner(env);assert.ok(next);await assert.rejects(heartbeatRunner(env,token),/lease_lost/);await releaseRunner(env,token,99);assert.equal(DB.raw.prepare('SELECT token FROM external_runner_leases').get().token,next);await releaseRunner(env,next,1);assert.equal(DB.raw.prepare('SELECT jobs_completed FROM external_runner_leases').get().jobs_completed,1);});
async function computeFixture(){const DB=makeDb(),id=await seedProject(DB,{candidates:1,reviewer:0,episodes:0});DB.raw.exec("DELETE FROM simulation_runs; DELETE FROM validations; DELETE FROM approvals; UPDATE projects SET status='running'; UPDATE design_candidates SET status='pending';");const content={research_question:'test',design:{max_candidates:1},constraints:{loss_max:10,loss_exceed_max:1,fp_max:1,fn_max:1,review_burden_max:1,recovery_time_max:100,confidence:.95},benchmark:{horizon:10},validation:{exploration_n:10,confirmation_n:10,robust_n:10}};DB.raw.prepare('UPDATE definitions SET content_json=?').run(JSON.stringify(content));return {DB,id};}
test('interrupted candidate unit resumes stored results without duplicating evidence or follow-ups',async()=>{const {DB,id}=await computeFixture(),env={DB,COMPUTE_EXECUTOR:'github-actions',EXTERNAL_RUNTIME:'github-actions',RUNNER_CODE_REVISION:'test-commit'};const a=await computeCandidate(env,id,'cand_0','exploration',0),b=await computeCandidate(env,id,'cand_0','exploration',0);assert.equal(a.id,b.id);assert.equal(a.loss_mean,b.loss_mean);assert.equal(DB.raw.prepare('SELECT COUNT(*) n FROM simulation_runs').get().n,1);assert.equal(DB.raw.prepare('SELECT COUNT(*) n FROM candidate_evidence').get().n,1);assert.equal(DB.raw.prepare("SELECT COUNT(*) n FROM jobs WHERE phase='confirmation'").get().n,1);const ev=JSON.parse(DB.raw.prepare('SELECT result_json FROM simulation_runs').get().result_json);assert.match(ev.result_hash,/^[a-f0-9]{64}$/);assert.equal(ev.runner_code_revision,'test-commit');DB.raw.exec('UPDATE projects SET evidence_revision=evidence_revision+1');bust(env,id);const next=await computeCandidate(env,id,'cand_0','exploration',0);assert.equal(next.id,a.id);assert.equal(DB.raw.prepare('SELECT COUNT(*) n FROM simulation_runs').get().n,1);});
test('Actions orchestration works against authenticated REST adapter and durable database',async()=>{const {DB,id}=await computeFixture();const remote=createD1Rest({...creds,fetchImpl:async(_url,o)=>{const {batch}=JSON.parse(o.body);const result=await DB.batch(batch.map(s=>DB.prepare(s.sql).bind(...s.params)));return Response.json({success:true,result:result.map(r=>({...r,success:true}))});}});const out=await runActions({DB:remote,COMPUTE_EXECUTOR:'github-actions',EXTERNAL_RUNTIME:'github-actions',MAX_JOBS_PER_TICK:1},{maxJobs:2,seconds:1});assert.equal(out.failures,0);assert.equal(DB.raw.prepare('SELECT COUNT(*) n FROM simulation_runs').get().n,1);assert.ok(out.d1_api_calls>0);assert.ok(DB.raw.prepare('SELECT last_completed_at FROM external_runner_leases').get().last_completed_at);});
